### PR TITLE
replace version-4 branch with master

### PR DESCRIPTION
**Pull request by benmccann**
opening a new PR tries to send it to https://github.com/vitejs/vite-ecosystem-ci. you think there's a setting you can tweak to stop that? (btw, @antony the same thing happens on https://github.com/sveltejs/eslint-config - it tries to send it to the beyonk one since that's where it's forked from)

### CODE REVIEW

**Review by dominikg — APPROVED** [review]
You did a text search for version-4 I suppose. If not please check for other instances, the default branch config is a bit verbose unfortunately

**Comment by dominikg** [comment]
Regarding default merge target I'm not sure

**Comment by benmccann** [comment]
Yes, I just did a search for `version-4`. What would the default merge target be if not `master`?

**Comment by dominikg** [comment]
> Yes, I just did a search for `version-4`. What would the default merge target be if not `master`?

I didn't find an option to change the target repo from the fork parent to this repo

**Pull request merged**
